### ISSUE TITLE
Criar template

### ISSUE THREAD

**Issue by somatorio** [mentoriaiac/Makefiles#1]
Precisamos de um template para ser utilizado nos outros projetos

**Comment by afonsoaugusto** [comment]
Podemos levantar uma possibilidade

**Comment by afonsoaugusto** [comment]
Criei o fork https://github.com/afonsoaugusto/Makefiles para tratar esta issue.

**Comment by afonsoaugusto** [comment]
@somatorio e @gomex, o que vcs acham de fechar essa issue agora que já fizemos o primeiro merge e irmos evoluindo o repositório a partir de outras issues mais especificas?
Por exemplo:
* Alterar terraform.inc para utilizar containers ao inves de invocar o binário diretamente
* Criar documentação básica sobre Makefile. #2 
* Alterar test com terraform para utilizar o Makefile raiz ao invés de copiar e versionar um copiado

**Comment by somatorio** [comment]
pra mim faz sentido
