### ISSUE TITLE
Evitar usar comandos da máquina e usar docker para isso

### ISSUE THREAD

**Issue by gomex** [mentoriaiac/Makefiles#5]
A ideia é que cada comando necessário para executar todos os passos do Makefile sejam executados dentro de um docker e assim uma pessoa que acabou de pegar o projeto não precise instalar nada pra executar os comandos.

Exemplo:

```
terraform-generate-backend:  ## Generate file backend.tf
	echo "STEP: terraform-generate-backend - Generate file backend.tf"
	cd ./${TERRAFORM_FOLDER}/ && \
	echo -e "terraform {\nbackend "s3" {}\n}" > backend.tf && \
	terraform fmt
```

Ao invés de ```terraform fmt``` isso poderia ser um ```docker run -it -v $PWD:/code -w /code hashicorp:terraform:${TERRAFORM_VERSION} fmt``` 

Claro que há várias formas de fazer isso e achar a melhor delas faz parte dessa issue também ;)

**Comment by marcelomansur** [comment]
Foi aberto o PR #8 para resolver essa issue.

**Comment by marcelomansur** [comment]
@gomex essa issue pode ser fechada.
