### ISSUE TITLE
Melhorar os testes no CI

### ISSUE THREAD

**Issue by gomex** [mentoriaiac/Makefiles#7]
Como passo seguinte na evolução desse CI seria bom termos as seguintes funcionalidades:

### Testar o terraform da pasta test/terraform

Rodar o ```make test``` a partir dessa pasta.

Essa parte depende da issue: #6 ser feita primeiro.

### Testar o download do REMOTE_MAKEFILE

Hoje esse teste não está no CI, mas deveria estar pra validarmos esse comportamento.

**Comment by marcelomansur** [comment]
O PR #8 melhorou os testes no CI executando o `make test` a partir do diretório `examples/terraform/local-backend`.

Falta testar o download do REMOTE_MAKEFILE.

**Comment by gomex** [comment]
Muito bom!
